# Generated by Django 3.0.5 on 2020-07-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200406_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('purchase', 'Product is for purchase'), ('bid', 'Product is for bid'), ('both', 'Product is for both')], default='purchase', max_length=35),
        ),
    ]
