# Generated by Django 3.0.5 on 2020-07-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_transactions_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('pending', 'Order is Pending'), ('rejected', 'Order is Rejected'), ('approved', 'Order is Approved')], default='pending', max_length=32),
        ),
    ]
