# Generated by Django 3.0.5 on 2020-07-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_transactions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
