# Generated by Django 3.0.5 on 2020-07-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_transactions_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='quantity',
        ),
    ]
