# Generated by Django 3.0.5 on 2020-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_remove_transactions_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='ZIP',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='transactions',
            name='adressLine1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='transactions',
            name='adressLine2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='transactions',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='transactions',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='transactions',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
