# Generated by Django 3.0.5 on 2020-08-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_bidhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='maximumBid',
        ),
    ]
